version: '3.6'

services:

  backend: 
    image: openjdk:17
    ports:
      - 8088:8080
    tty: true
    volumes:
      - ./onlineshop:/srv:cached
    working_dir: /srv
    depends_on:
      - mysql

  mysql:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    container_name: onlineshop-mysql
    volumes:
      - ./mysql/log/:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3326:3306
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"